### ISSUE TITLE
Windows: ls command not working

### ISSUE THREAD

**Issue by jesusprubio** [IBM/kui#1304]
It hangs the actual tab. The shell is blocked even in new tabs.

(Option 2: Double-clickable app Download)

**Comment by starpit** [comment]
thanks for the bug report; can you try `pwd` ? i suspect that this is due to us not building the node-pty binary for windows properly -- to do this right, for now, we will need to build our windows distribution *on windows*; we are currently building the windows distribution on linux.

the underlying issue here is that node-pty-prebuilt has not kept up with releases of node-pty; the result is that we cannot rely on it, and have to build node-pty ourselves.

**Comment by starpit** [comment]
if my suspicion is true, the javascript console should show something like 

> cannot load lib/Debug/pty.node

**Comment by jesusprubio** [comment]
For `pwd` is a bit different

![image](https://user-images.githubusercontent.com/2753855/57435445-bb275780-723d-11e9-9837-c01b68586498.png)

And new tabs keep working:
![image](https://user-images.githubusercontent.com/2753855/57435488-d3977200-723d-11e9-8ce8-ba5bd4e20c3d.png)

**Comment by jesusprubio** [comment]
BTW `dir` also fails, so probably we have different problems.
![image](https://user-images.githubusercontent.com/2753855/57435668-3db01700-723e-11e9-85c4-a17fd94d32e8.png)

**Comment by jesusprubio** [comment]
`ls`
![image](https://user-images.githubusercontent.com/2753855/57435701-5a4c4f00-723e-11e9-8778-5990830b15bd.png)

`pwd`
![image](https://user-images.githubusercontent.com/2753855/57435746-75b75a00-723e-11e9-94f7-b986cdeb5f0a.png)

**Comment by starpit** [comment]
thanks! upon further reflection, i suspect that the `pwd` bug is indeed the pty build issue; but `ls` is probably separately solvable. i'll take a look.

**Comment by starpit** [comment]
i think we might be good to go here, with #3332 and 5.5.8

**Comment by starpit** [comment]
it turns out that windows ls works fine when kui is launched with git-bash, but not if it is launched from powershell
