### ISSUE TITLE
OpenWhisk remnants in core-support help command

### ISSUE THREAD

**Issue by myan9** [IBM/kui#166]
https://github.com/IBM/kui/blob/3ebbbad0a3e8797423328ce93299da9724d66ef7/app/plugins/modules/core-support/src/lib/cmds/help.ts#L26
https://github.com/IBM/kui/blob/3ebbbad0a3e8797423328ce93299da9724d66ef7/app/plugins/modules/core-support/src/lib/cmds/help.ts#L114-L118

**Comment by starpit** [comment]
we should address this by adding a `noDefaultContext` feature to the command-tree resolver; this flag allows a command to indicate that it should only resolve with a fully qualified context, e.g. `wsk action help` rather than `help` where the default execution context is `wsk action`.

perhaps we should call the flag `requiresFullyQualifiedCommands`

labeling as enhancement for this reason

**Comment by starpit** [comment]
i'm going with `requiresFullyQualifiedRoute`
