### ISSUE TITLE
table watcher may result in oddly empty space when all rows go away

### ISSUE THREAD

**Issue by starpit** [IBM/kui#1779]
this looks kinda weird:

![Screen Shot 2019-06-19 at 12 00 15](https://user-images.githubusercontent.com/4741620/59781473-d8623380-9289-11e9-904f-bbe7b736a732.png)

**Comment by myan9** [comment]
Thanks! In this case, the expected result is the status badge changing from Ready(or Active) to Offline. 
We didn't get the expected behavior because I kinda hardcoded the error message to the resource deletion mechanism: ```if (err.code === 404 && err.message.includes('No resources')) ```. The error message is ...not found... in your case.

To solve this issue, I removed the err.message check since it seems not necessary. However, I think a more problematic issue this this issue exposed is that, we didn't handle the error case very well in formatTable().  When something bad happened in refreshing command, we couldn't format a nice error message like our normal command. Deeper work needed.
