### ISSUE TITLE
Long output gets truncated

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1883]
I was testing out several third party CLI tools in KUI and noticed that a lot of them were working.  However, I noticed a strange behavior when using a CLI tool called `popeye` (https://github.com/derailed/popeye).  The output from the `popeye` command prints out a long report about a kubernetes cluster.  Most of the report gets truncated; but in a standard desktop terminal the full report can be seen.  I am using a Mac.

**Comment by ydarias** [comment]
I have the same problem at macOS.

![image](https://user-images.githubusercontent.com/948946/60800288-4016ea80-a175-11e9-9c9e-321cfc759ae7.png)

**Comment by starpit** [comment]
confirmed. you can see it even with just `cat README.md` from the kui repo
the issue here is that the underlying xterm.js manages a scroll region. when the underlying process terminates, we need to find a way to grab the entire region, not just the viewport that was visible upon termination.

**Comment by showeimer** [comment]
@ydarias any update on this problem?  I am taking a look at it now, and it seems very complex, wanted to see if you had any findings.

**Comment by starpit** [comment]
i don't think requires very many changes, as long as we are willing to tolerate inner scrolling:

1) comment out lines 1039 and 1040 in client.ts
2) comment out lines 7 and 10 in xterm.css

then i think at least we have a workable temporary solution to this issue

**Comment by starpit** [comment]
andthe UX problem we face with inner scrolling is not just cosmetic. it affects the flow of rapid scrollwheel or multitouch-swipe scrolling. because as you continue to scroll up (or down) what was initially resulting in scrolling of the kui scroll region may change to scrolling an inner scroll region; once that inner scroll region is in focus, no matter how much you swipe up, you won't swipe out of that region

thus, a better fix would include some sort of

3) when the xterm.js region is at scrollTop, then somehow relinquish focus on the next scroll-up event, so that that scroll can occur in the enclosing region; similarly for scrollBottom and scroll-down

**Comment by showeimer** [comment]
@starpit thanks, you mentioned all the issues I was about to comment on.  I think the inner scrolling in general is really odd.  I'm not sure the user will know that they need to scroll on top of the xterm output div because 1. a normal terminal does not have this behavior, 2. it is not obvious to the user that div is scrollable/needs to be scrolled to see more data.  Is the xterm div forced to be that size because of some row configuration?  I think it will also be frustrating to the user to have to guess what part of the right margin to hover over just to scroll the main repl output and not the xterm output.

**Comment by starpit** [comment]
xterm.js needs to know the rows and cols of the canvas because of the semantics of PTYs. an application, such as `less`, should be able to know how tall the canvas is, in units of lines, so that it can control pagination.

i have been thinking that the right answer here is to observe when we have long output, and sequester this to the sidecar. this would be a variant of my point 4 above. i.e. everything is fine, until nLinefeeds > nViewportRows. even though applications are allowed to delete lines, this upper bound approximation would be pretty fine. 

we already do this for a few special cases, such as `cat somefile.json` or `cat somefile.yaml`, which just preemptively redirect the content to the sidecar (and to the editor view)

**Comment by showeimer** [comment]
@starpit agreed the right fix is complicated at this point, maybe we can have a discussion tomorrow about it with the others to determine what the right fix is short-term and long-term.

**Comment by starpit** [comment]
the answer that would eliminate all of these issues would be to add a `Terminal.write(content: Element)` method (right now, you can only `Terminal.write(content: string)`

if we added support, to the xterm.js base, to inject preformatted content, then we'd be playing all in one sandbox.

**Comment by starpit** [comment]
i personally am fine with the sequester-to-sidecar approach. who wants 500 lines of output polluting their sidecar, anyway. most of the time this output is transient, which is perfectly in keeping with the sidecar design point.

**Comment by starpit** [comment]
ok, the final idea that i had been playing around with, and that might actually work. sorry that i didn't cover it above, i only now remembered the idea:

the only reason xterm.js "hides" content under a scrollbar is that it was told the viewport has fewer rows than does the content. if we adjust its concept of nRowsInViewport after termination, and then, only after the final refresh, capture the xterm thus removing the scrollbars... this should work. 

there are a few nuances, mostly related to one of the larger issues/bugs in xterm.js: there is no way with certainty to know that it is actually down refreshing all of the rows. for example, sometimes we get *two* `onrefresh` callbacks, and the indicated rowspan is the entire viewport. we need to wait for the second one... but how can we know that more refresh events are pending, if the first event told us that the entire viewport was refreshed, and we have written no more content in the mean time...??

anyway, part of the reason for the complexity in our code is to work around this bug. so i have some experience with doing so, already.

so far, this change seems pretty stable. i'll poke a bunch more at it.
