### ISSUE TITLE
Dark mode - large gray visual defect in sidecar tables

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2452]
<img width="1572" alt="Screen Shot 2019-08-21 at 10 12 27 AM" src="https://user-images.githubusercontent.com/26075187/63439556-4b0f9c80-c3fc-11e9-8827-bb1a22f9ca3c.png">

<img width="900" alt="Screen Shot 2019-08-21 at 10 21 50 AM" src="https://user-images.githubusercontent.com/26075187/63440567-0be24b00-c3fe-11e9-9a02-fe024a0711df.png">

<img width="317" alt="Screen Shot 2019-08-21 at 10 25 43 AM" src="https://user-images.githubusercontent.com/26075187/63440615-21f00b80-c3fe-11e9-86c4-2147437d112d.png">

Gray borders/lines also appear when hovering over rows.  Some table cells will always have a gray border.

**Comment by starpit** [comment]
thanks! this is due to some css bugs in the core. 

1) lack of vertical-align: middle for table cells; i'm not sure why the carbon components base does not specify this for its own tables

2) some cells are not getting a display: table-cell, due to a kui css bug; as a result, they do not span the full height of the row; this, combined with the lack of a cell-colored background color on the table, leads to the white gaps
