### ISSUE TITLE
usage output should not display as an error

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2612]
<img width="700" alt="Screen Shot 2019-08-30 at 12 04 01 PM" src="https://user-images.githubusercontent.com/26075187/64035283-61190d80-cb1e-11e9-8e05-c2eec2eab0cf.png">
<img width="708" alt="Screen Shot 2019-08-30 at 12 04 08 PM" src="https://user-images.githubusercontent.com/26075187/64035284-61190d80-cb1e-11e9-92be-8ef22fb9d995.png">

bash-like does not have this issue.

**Comment by starpit** [comment]
i also don't see these, and so will need some more information.

**Comment by showeimer** [comment]
@starpit are you testing these issues on electron or webpack?  All I'm doing is running `kubectl` or `helm`.

<img width="764" alt="Screen Shot 2019-08-30 at 12 32 39 PM" src="https://user-images.githubusercontent.com/26075187/64036926-5ceeef00-cb22-11e9-9141-9bd5d17dda3a.png">

**Comment by starpit** [comment]
i am trying webpack+proxy

**Comment by starpit** [comment]
if you don't see "rejecting as usage error" then something is wrong. 

![Screen Shot 2019-08-30 at 12 51 07 PM](https://user-images.githubusercontent.com/4741620/64037961-e6072580-cb24-11e9-99b3-b82eb340d1f1.png)

**Comment by starpit** [comment]
sorry, i was confused. this is not a statement about the overall nature of the output. rather than some help output is designated as an error. we probably need another category, but kui itself needed a way to distinguish between normal response and preformatted usage. since the result thusly has a non-zero exit code, the CLI blindly displays this with the error icon.

**Comment by starpit** [comment]
should be resolved now. kubectl usage is displayed in the LeftNavSidecar component
