### ISSUE TITLE
Pod events tab empty state message

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2882]
<img width="283" alt="Screen Shot 2019-09-30 at 10 40 40 AM" src="https://user-images.githubusercontent.com/26075187/65889250-ef2b2280-e36e-11e9-847d-8a01cdf6f089.png">

Pod events are not a resource, this message should say `No events found.`

**Comment by myan9** [comment]
@showeimer Thanks for reporting the issue! 

The content in Events Tab is the execution result of command `kubectl get events --field-selector involvedObject.name=...` and `-o custom-columns`. 

So, the message `No resources found` is actually from `kubectl`. (FYI: I explicitly wrote the string`No resources found` in the events tab implementation code just because the error message is lost when the output format is custom-columns.) 

Another concern: Events is actually in Kubernetes resource list, so I'd say the return message is at least not wrong. https://kubernetes.io/docs/reference/kubectl/overview/#resource-types

We could discuss if we want to improve this message from UX standpoint.

**Comment by showeimer** [comment]
@myan9 good find!  I think this behavior is okay then, usually from UI standpoint it is better to be more explicit in what exactly is missing; but for KUI it is probably better to just return the CLI message.  I'll close the issue.
