### ISSUE TITLE
plugin compiler should handle absence of document and window more gracefully

### ISSUE THREAD

**Issue by starpit** [IBM/kui#306]
maybe by leveraging mimicDom from headless.ts

as a side point, we probably should try catching exceptions and not repeating them 100 times -- the plugin compiler has an iterate-till-convergence approach.

**Comment by joshuaauerbachwatson** [comment]
Part of the original motivation for this issue was my experience fighting the pre-compiler while developing a plugin.   Based on additional insight:
1.   In my case, the entire problem was due to having quickly converted a JS file to TS and then quickly making the TS into a module by adding exports.   The plugin compiler loads modules, so anything left around at module scope (not inside functions) will execute seemingly "at compile time" and I didn't realize that!   I actually had no need for document or window to be available at module load time, only at runtime after loading.   Reorganizing the code fixed the problem.   Offering mimicDom would not have fixed all of my problems (just moved me on to the next problem caused by the underlying misunderstanding).
2.  I am not sure going down the road of making more things work during plugin compile is right ... it feels too open-ended to me.
3.  Suppressing the 100 repetitions of the error does seem like a good idea.
4.  I think this issue should be repurposed as addressing better documentation of what happens during plugin compile (including mentioning this gotcha) and perhaps some strategy to notice common developer errors and provide hints when things go wrong.

**Comment by starpit** [comment]
nope, still a bug or two
