### ISSUE TITLE
Sidecar screenshot button is available despite command not being supported

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#3577]
<img width="64" alt="Screen Shot 2020-01-29 at 11 08 33 AM" src="https://user-images.githubusercontent.com/26075187/73374269-eea48900-4287-11ea-8260-af08f144a8da.png">
<img width="499" alt="Screen Shot 2020-01-29 at 11 08 38 AM" src="https://user-images.githubusercontent.com/26075187/73374267-eea48900-4287-11ea-8517-a156418d3275.png">

---

KUI should do some kind of command/service discovery on features like this so that the user is not presented with functionality that won't work.

**Comment by starpit** [comment]
thanks. the underlying issue here is that the screenshot button is hard-coded into our index.ejs. whereas it should be a contribution by the screenshot plugin. 

right now, there is no extension point that allows for contributions to the title stripe of the sidecar. we already allow for contributions to tabs and badges, so this would probably be a fairly small bit of extra work.

**Comment by showeimer** [comment]
Just to add on, this button is also available on every command in the repl despite the capability not being available.

**Comment by starpit** [comment]
thanks for the clarification. this part of the core hasn't changed, i think, since your last release? is it possible that you used to have some display:none rules? if not, could you add some, for now?

**Comment by showeimer** [comment]
Yeah we can add that for the time being

**Comment by starpit** [comment]
fixed by #3623
