### ISSUE TITLE
action rm <a> prints ok but does not delete <a>

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#477]
is action rm an alias for action delete?
it prints ok but the action is not deleted.

**Comment by starpit** [comment]
in order to avoid conflicts with the normal UNIX `rm`, we had to rename the openwhisk `rm`. currently, the previous `rm` is awkwardly named `rimraf`, as it supports recursive removal of packages. it still supports multi-delete and wildcards. you may change the name in a PR.

deeper: for openwhisk-oriented clients, the default command context is `/wsk/action`. this means that if we were to use `rm` for the name of the fancier openwhisk removal command, there would be no recourse for requesting the normal UNIX `rm`. 

we could consider changing the default execution context to `/`. i think that if we were to do this, we could restore `wsk xxx rm`.

**Comment by starpit** [comment]
the "prints ok" part should be resolved now.
