### ISSUE TITLE
Cursor keys work poorly in the terminal

### ISSUE THREAD

**Issue by andrewnazarov** [IBM/kui#4882]
**Describe the bug**
It's almost impossible to use cursor keys in terminal mode. It produces some input instead of actual cursor movements.

**Steps to reproduce the behavior**

1. Go to terminal
2. Try to use cursor keys

**Expected behavior**
Cursor movements and corresponding actions.

**Screenshots**
<img width="612" alt="Screenshot 2020-06-12 at 21 19 24" src="https://user-images.githubusercontent.com/11255710/84534501-acd62580-acf2-11ea-8494-0bf08b9691c3.png">

**System**

- Kui version: 8.8.2
- Operating system: macOS Mojave 10.14.5

**Comment by starpit** [comment]
wow, thanks for the bug report!

**Comment by starpit** [comment]
i see. this is because we use `sh` as the login shell. in some containers, `sh` happens to be a shell that supports command history. in others (e.g. this seems to be the case for alpine containers), `sh` does not support command history.

i.e. this is a property of the container, rather than of kui.

we chose to use `sh`, because it is guaranteed to be available in any linux container.

thoughts: you could launch e.g. `bash` (which is often included in containers), which will give you command history. beyond that, i'm not sure how to get bash-when-available in a stable way. we could experiment, though.

**Comment by andrewnazarov** [comment]
But it's not only the bash history which is affected but the cursor movement (from right to left, from left to right) as well.

**Comment by starpit** [comment]
hi, thanks for the clarification!

indeed. this is also an issue with the shell being used, rather than with Kui. e.g. using one of the test pods from Kui's test suite, and using a plain terminal (i.e. not Kui):

```bash
kubectl apply -f https://raw.githubusercontent.com/IBM/kui/master/plugins/plugin-kubectl/tests/data/k8s/kubectl-logs-two-containers.yaml
kubectl exec -it kui-two-containers sh
Defaulting container name to nginx.
Use 'kubectl describe pod/kui-two-containers -n default' to see all of the containers in this pod.
# ^[[A^[[D^[[C^[[B
```

the last line is me typing the four arrow keys. whereas if i launch `bash` from within that session (or specify bash rather than sh when connecting via `kubectl exec`), then arrow keys work.

some containers have a more modern `sh` by default, some have a very primitive `sh` by default (as is the case with this kui-two-containers demo).

it'd be nice if Kui could detect the availability of e.g. `bash`, and use that to initiate a session (in the Terminal tab). any ideas here would be most welcome. off the top of my head... we could attempt a `bash -- echo hi`:

```bash
kubectl exec kui-two-containers bash -c nginx -- echo hi
hi
```

this would add a non-trivial amount of latency to the Terminal connection (500ms-1s for my cluster!), which is why we have defaulted to "good old sh" for now.

**Comment by andrewnazarov** [comment]
Yeah, pretty clear to me. Also can't figure out what could be a nice solution for this. Thanks for the answer!

I'm amazed by the maintenance of this project, by the way. You are doing great!
