### ISSUE TITLE
Switching between tabs does not put focus in command entry field  

### ISSUE THREAD

**Issue by chrisahl** [IBM/kui#5102]
**Describe the bug**
When I switch between tabs, I would like to be able to type new commands immediately.  However, the focus is not in the command entry field.  This means I have to move the mouse to the command entry field and click before typing.

**Steps to reproduce the behavior**

1. Open at least 2 tabs
2. On tab 1, enter a command
3. Switch to tab 2, you cannot enter a command right away, you must first click in the command entry field
4. Switch to tab 1, same thing occurs

**Expected behavior**
When you switch to a tab, the cursor should be in the command entry field

**System**

- Kui version: 8.10.11
- Operating system: ACM/OCM

**Comment by mark-nc** [comment]
This bug occurs only if the bottom input stripe is present because the `hackFocus()` function in TabContainer.tsx is only looking for `.replActive input` inside the active tab container.  It should also check if `.replActive input` is located inside `kui--input-stripe.repl`.  See https://github.com/IBM/kui/blob/5490556d7f635fff86e85667b1ada610a99e0784/plugins/plugin-client-common/src/components/Client/TabContainer.tsx#L69
