### ISSUE TITLE
Output of `kubectl get namespaces` and `oc get namespace` behave differently

### ISSUE THREAD

**Issue by chrisahl** [IBM/kui#5106]
**Describe the bug**
Output of `kubectl get namespaces` and `oc get namespace` behave differently

`kubectl` returns a table in which you can change the current namespace, but does not open sidecar
`oc` returns a differently formatted table where selecting the namespace opens the sidecar, but does not change the current namespace

**Expected behavior**
Both calls would produce the same output format and operation.  I can see where setting the namespace if valuable but there is also use (although small) in being able to see the namespace object in the sidecar.  So not 100% sure that sidecar view should be lost if we just go with `kubectl` style 

**Screenshots**
![image](https://user-images.githubusercontent.com/32707829/87070037-32f86580-c1e6-11ea-9bcc-5c1be50b9f6c.png)

![image](https://user-images.githubusercontent.com/32707829/87070288-8ff41b80-c1e6-11ea-9602-d66de7639363.png)

**System**

- Kui version: 8.10.11
- Operating system: ACM/OCM

**Comment by starpit** [comment]
excellent catch!

**Comment by chrisahl** [comment]
Well, to be honest, we are getting lots more eyeballs on this now and we are getting questions from the field, which have generated the creation of this issue.  So not just my eyeballs...

**Comment by mark-nc** [comment]
In a discussion on this yesterday it seemed best if `kubectl get namespaces` and `oc get namespaces` both just display the table of namespaces and let you select one as the current context.  That makes it do one thing rather than two (i.e., also open the sidecar).  `kubectl describe namespace <namespaceName>` or `oc describe namespace <namespaceName>` will get the same sidecar contents and that is the more obvious command to get at details.
