### ISSUE TITLE
Events for past day

### ISSUE THREAD

**Issue by dex4er** [IBM/kui#5347]
Hi. I would like to see events for past day (or week?), not just past hour. Would it be possible to browse events for longer period?

Thanks!

**Comment by starpit** [comment]
Hello, and thanks for the issue!

This one-hour limit is baked into the default settings for the Kubernetes apiserver. To address this would require a change to your cluster configuration. Either you can adjust the `--event-ttl` parameter passed to kube-apiserver, or you may set up an external event substrate. The underlying issue is that etcd is not set up to handle a large volume of events, and so the Kubernetes core team made a decision to limit the number of events pretty harshly.

ref: https://github.com/kubernetes/kubernetes/issues/52521

**Comment by dex4er** [comment]
Hi. It seems that we should close the issue. This is not related to Kui. Or maybe Kui should replace "No events in the past hour" message with something less hardcoded if it might be adjusted with `--event-ttl` parameter.
