### ISSUE TITLE
creating a minisplit will show ‘Created a split’ in the previous focused minisplit

### ISSUE THREAD

**Issue by myan9** [IBM/kui#5690]
The 'Created a split' seems unnecessary in this case. It also hides the the previous command in a mini-split, which is more important to show

![Screen Shot 2020-09-18 at 1 12 44 PM](https://user-images.githubusercontent.com/21212160/93625885-a5d54800-f9b0-11ea-83ad-8bc96d2c0acf.png)

**Comment by starpit** [comment]
Solving this truly an deeply might require a bit more thinking as to the sequence of splits. Right now, it is:

1 full page split
2 half-width, full-height splits
3 with two minisplits and one full-height, 2/3rd-width split
4, 5 each with one additional minisplit

The hard one is the transition between 2 and 3, which requires a transition from 0 minisplits to 2 minisplits. This means that one of the existing regular splits must be transitioned to become a minisplit.

This problem is compounded by the facts that a) minisplits only show one block at a time; and b) we transition the first split to become one of the new minisplits; c) the "created split" blocks also appear in the first split! So we have shot ourselves in the foot, because the final block (prior to creating that third split) will not be visible -- instead the user will only see "Created a split".

The short-term fix might be just not to show these kinds of breadcrumb blocks in minisplit presentations.
