### ISSUE TITLE
kui 9.2.0 broken

### ISSUE THREAD

**Issue by Supesharisuto** [IBM/kui#6264]
**Describe the bug**
kui mac os prebuilt binary yields blank page
**Steps to reproduce the behavior**

    cd /usr/local/bin;
    curl -L https://github.com/IBM/kui/releases/download/v9.2.0/Kui-darwin-x64.tar.bz2 | tar jxf -;
    export PATH=$PWD/Kui-darwin-x64/Kui.app/Contents/Resources:$PATH

**Expected behavior**

beautiful kui shell

**Screenshots**
![image](https://user-images.githubusercontent.com/45889594/100395006-12457680-2ff4-11eb-86ac-bc05bde44cb6.png)

**Code snippets**
 > kui
(electron) 'allowRendererProcessReuse' is deprecated and will be removed.

**System**

- Kui version: 9.2.0
- Operating system: macos Mojave

**Comment by starpit** [comment]
Hi, thanks for the bug report! I think this will be fixed with 9.2.3, which will be released shortly. To help us make sure, can you confirm this guess: you are using Kui in "popup" mode, as a kubectl plugin? If so, indeed there was an oops with that path that should be resolved once 9.2.3 is out.

Re: the warning message: it is innocuous, but for 9.2.4, we will look into whether it is possible to squash this message. Longer story: this is due to the `node-pty` module not yet behaving as a context-aware native module, and Electron has started to be more forceful in warning us of this fact. ref: https://github.com/microsoft/node-pty/issues/405

**Comment by Supesharisuto** [comment]
hi. I used it in popup mode but kubectl-kui seems also broken
I backed out to 9.1.0 and everything is working again.
Thanks for the prompt response

**Comment by starpit** [comment]
No worries, we really appreciate the feedback. Keep it coming!

**Comment by starpit** [comment]
9.2.3 is out. When you get a chance, let us know if this resolves your issues. 9.2.3 fixes a few popup-related issues, including lack of persistent focus in the input element, and failures during startup in some cases.

**Comment by Supesharisuto** [comment]
It works! Nice help pages with link on 'Welcome to Kui'
Thanks so much

**Comment by starpit** [comment]
That's great to hear, thanks for letting us know. The welcome page is an example of a Notebook. You can make your own, and if you want to PR any notebooks back so that others can see them, feel free! You should also see a "Making a Notebook" notebook from the Notebooks OS-level menu (e.g. from the menubar on macOS).
