### ISSUE TITLE
sometimes response is not scrolled into view properly

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6479]
With commands that take longer to complete, sometimes the bottom of the command response is not scrolled into view. This might because of race condition. 

Also, when user clicks a table row in a notebook, the sidecar response won't be scrolled into view.

**Comment by starpit** [comment]
I wonder if the setTimeout in Input can be adjusted at least to improve the situation a bit. The problem seems to come from two sources of rendering lag:

1) some React components and CSS are loaded lazily, so the first time a particular kind of view (e.g. a table, or monaco) the height of the Output will change after the command has completed. This is because the component render() functions are asynchronous w.r.t. Kui's REPL.

2) some views may change their height shortly after being loaded. e.g. the height of a monaco-editor instance varies slightly, depending on the content being presented
