### ISSUE TITLE
oc get po got hang

### ISSUE THREAD

**Issue by yuecchen** [IBM/kui#7040]
oc get po command got hang, while other commands runs well:
 
![image](https://user-images.githubusercontent.com/24837518/108381565-e3c9e700-7242-11eb-86e2-92a1c5807f50.png)

Reproduction steps(there are some useless steps because I'm not familiar with the build steps):

1. download 10_1_x tag code: https://github.com/IBM/kui/archive/10_1_x.zip
2. run `npm ci & npm start`  ( cannot access through web browser)
3. run 
```
npm run kill
npm run kill:proxy
npm run kill:cproxy
```
4. run `npm run watch`
5. run `npx kui-build-webpack`
6.  run 
```
npm run kill
npm run kill:proxy
npm run kill:cproxy
```
7. run `npm run watch:webpack`
8. access `http://localhost:9080`

Here are some other screenshots:

1. errors on page loading:
![image](https://user-images.githubusercontent.com/24837518/108382008-576bf400-7243-11eb-9388-b9d68e2d07b4.png)

2. some websocket traffic:

![image](https://user-images.githubusercontent.com/24837518/108382221-897d5600-7243-11eb-96fe-383b6f3c6b8e.png)

**Comment by myan9** [comment]
Hi Yue! Thanks for the issue report! Your first warning screenshot indicates that, for some reason, the nodejs sourcemap failed to be served by webpack dev-server, which sometimes makes it hard for us to stack trace, but is innocuous. Can you put `-Devtool -sockjs` in the console filter bar to eliminate these warnings, and open the console sidebar to see if there's any console errors?

![Screen Shot 2021-02-18 at 11 39 50 AM](https://user-images.githubusercontent.com/21212160/108389802-037af400-71de-11eb-8df1-e4c1a15e4eb6.png)

Since you built Kui successfully, we guess Kui failed handling at oc commands. This could be an authentication error, since Kui v10 handles most of the Kuberentes commands by using Kubernetes API directly and authorizing users via kubectl proxy. We might miss some cases for oc commands. If there's no console error, can you put `fetch` in the console filter bar and take a screenshot? This could tell us whether fetch-file succeeded. Thanks!

![Screen Shot 2021-02-18 at 11 41 10 AM](https://user-images.githubusercontent.com/21212160/108389983-3329fc00-71de-11eb-9a93-2c0a4dd032b7.png)



3. filter the devtool results and see if you can paste the fetch content, fetchViaNeedle result

**Comment by yuecchen** [comment]
Thanks for the quick response.

I opened the log level to verbose then I got the colorful debug logs.

here are logs with `-Devtool -sockjs` filter, and they are for `oc get po` command only (clear early logs)
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/24837518/108446966-05a28880-729a-11eb-9e66-018ae0d5b8a4.png">



here are logs with `-Devtool -sockjs fetch` filter, logs in red rectangle are for `oc get po`, others are for window initialization
<img width="1291" alt="Screen Shot 2021-02-19 at 10 02 07 AM" src="https://user-images.githubusercontent.com/24837518/108447087-397dae00-729a-11eb-80df-11abd7df33d4.png">



BTW, here are what we got from local command line:
```
yuecchen@yuecchens-MacBook-Pro ~ % oc get po
No resources found in default namespace.
yuecchen@yuecchens-MacBook-Pro ~ % kubectl get po
No resources found.
```

and, for `oc login`, we are using IKS (IBM Cloud Kubenetes Service):
```
oc login --token=<login token> --server=https://c115-e.us-south.containers.cloud.ibm.com:31434
```
and for the first time usage, it require to install some additional tools:
```
curl -sL https://ibm.biz/idt-installer | bash
```


<img width="688" alt="image" src="https://user-images.githubusercontent.com/24837518/108447807-81e99b80-729b-11eb-80b9-1acbaad0b5f3.png">

**Comment by starpit** [comment]
thanks! It seems like the fetch-file is not responding. Is the proxy is running locally on that machine? If so does `ps aux | grep kubectl` show a `kibecrl proxy` process running? 

Also: did you run oc login after starting the kui proxy, or before? 

If you restart the kui proxy with an env var of DEBUG=* and pipe its output to s file, you should see the same kinds of log messages as you saw in the client dev tools. Any errors? Does the fetch-file show up?

I'll catch up again after sleep.

**Comment by yuecchen** [comment]
I ran `oc login` before start KUI (maybe not proxy?), and now I tried to run `oc login` in the KUI window, but the problem still exist

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/24837518/108449790-0c7fca00-729f-11eb-8fbc-11c5b863c9c8.png">

I set `deubg=*` and `DEBUG=*`

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/24837518/108449669-d0e50000-729e-11eb-9e7d-3e3fe54ca738.png">

when I tried to start a proxy, it says:

```
start proxy 64521
Port 8081 is already in use
```


I didn't find a way to pipe output to a file, I will try it later.

**Comment by starpit** [comment]
Thanks! To restart the proxy with DEBUG, try this:

```sh
npm run kill:proxy
DEBUG=* npm run proxy >& /tmp/kui-proxy-log.txt
```

Then revisit the browser client and try again. This time, that `/tmp/kui-proxy-log.txt` should have a log messages somewhat similar to what you see in the browser client's devtools console.

My guess is that there is some uncaught exception on the kui proxy side that is clogging things up. If so, it should be fairly easy to spot in that log file.

**Comment by yuecchen** [comment]
this issue got fixed with latest code

**Comment by starpit** [comment]
Thanks! The covering PR #7049
