### ISSUE TITLE
remove the injecting-config-at-build-time customization

### ISSUE THREAD

**Issue by myan9** [IBM/kui#834]
With PR https://github.com/IBM/kui/pull/833, we don't need the proxy config customization at build time any more

**Comment by joshuaauerbachwatson** [comment]
Just noting that the `config.json` injection is more general than just "disable-proxy" because any plugin or external client can consult the settings and define their own "injectable" parameters.  IMO It's a good way to support a build-time burn-in of something that will be a constant thereafter but might differ from build to build.  We have used it in that way in the past.   We aren't using it currently but would like to resume using it for something new.

I hope that if it is removed, you will document how to achieve the same effect without it.

**Comment by starpit** [comment]
agreed with not removing. we just need to cover this and a few related features with tests

**Comment by starpit** [comment]
closing for now
