### ISSUE TITLE
ls versus linux

### ISSUE THREAD

**Issue by myan9** [IBM/kui#869]
![Screen Shot 2019-03-15 at 3 58 48 PM](https://user-images.githubusercontent.com/21212160/54458834-536ff700-473b-11e9-86a7-bf450c613182.png)

**Comment by starpit** [comment]
this has nothing to do with webpack or proxy, it comes from ls versus linux (or windows for that matter).  it is probably impossible to pick apart the columns of `ls -lh` generally speaking, because the column schema is not presented in the output, and the minimum column separation is 1, which is indistinguishable from inter-word spacing within a column.
