### ISSUE TITLE
auth list infinite loop

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#964]
if you have existing `auth` added, then change the host to a bogus value and try `auth list` again, the shell is stuck in an infinite loop (have to refresh or kill the shell to regain control).

<img width="1172" alt="Screen Shot 2019-03-23 at 8 35 10 AM" src="https://user-images.githubusercontent.com/4959922/54866135-ae5eab00-4d46-11e9-8983-8d8b63b76724.png">

**Comment by starpit** [comment]
thanks for capturing this. i ran into this issue once, but then couldn't remember the steps i had taken to get to that bad spot!

**Comment by starpit** [comment]
hmm, this might be fixed? i can't yet duplicate it

**Comment by rabbah** [comment]
I updated to 9e64ddf919ab32fcfbbc66487910655a7ecb5e63 and hmm well I can't reproduce now with the same steps outlined above. I'll try some more.

**Comment by rabbah** [comment]
thank you @starpit - i can no longer produce including in custom client.

**Comment by joshuaauerbachwatson** [comment]
I believe this issue was closed in error.  I can't reopen it myself but hope someone else will.

The problem is tricky to reproduce (and it's possible that a particular sequence that used to reproduce it stopped doing so).   But, the bug is still with us.

1.  Build the latest kui (monorepo).
2.  Start kui shell and clear local storage.   Restart with local storage empty.
3.  Ensure a correct API host and create a valid auth.   Check that some "needs auth" commands are working correctly.
4.  Revoke the auth at the controller.   Wait 5 minutes or so for the controller's cache cycle.
5.  Do something in kui that requires auth and worked before (if it still works you didn't wait long enough).   The failure should probably be `The supplied authentication is invalid`
6.  Issue `auth list`.   It will loop infinitely in the three-phase throw sequence.

I find that the following (somewhat inadequate, quick and dirty) fix will break the infinite loop.
```
--- a/plugins/plugin-openwhisk/src/lib/models/namespace.ts
+++ b/plugins/plugin-openwhisk/src/lib/models/namespace.ts
@@ -166,6 +166,10 @@ export const setNeedsNamespace = async (err?: Error) => {
   // hasn't yet selected a namespace.
   if (err) {
     console.error(err)
+    if (err['statusCode'] === 401) {
+        setNoNamespace(false)
+        throw new Error('An authorization has become invalid.  A cleanup step is needed here')
+    }
   }
 
   debug('setNeedsNamespace')
```
The "cleanup step' that the message refers to is to drop the offending auth from the model, so that the user either goes back to having no auth, or has a list with one fewer entry.  I believe I could write the code to do that and might attempt it but there are no other examples in kui of deleting an auth from the model (IMO the user should also be able to do this manually).   Please confirm.

**Comment by rabbah** [comment]
@starpit are the commits above and corresponding PR tagging this issue incorrectly?
